version: 1

machine:
  services:
    - docker

dependencies:
  pre:
    - npm install -g npm

jobs:
  build:
    working_directory: ~/website/
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build